version: '3.7'

networks:
  default:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  adminer:
    driver: ${VOLUMES_DRIVER}
  backend_node_modules:
    driver: ${VOLUMES_DRIVER}
 

services:

  backend:
    build:
      context: ${DOCKER_BUILD_CONTEXT_DIR}
      dockerfile: docker/backend/node.Dockerfile
      args:
        - HTTP_PROXY=${APP_HTTP_PROXY}
        - HTTPS_PROXY=${APP_HTTPS_PROXY}
        - NO_PROXY=${APP_NO_PROXY}
    depends_on:
      - db
    tty: true
    restart: "no"
    ports:
      - "${BACKEND_WEB_HTTP_PUBLISH_PORT}:3000"
    networks:
      - default
    volumes:
      # - ${DOCKER_VOLUME_CODES_ROOT_DIR}/backend/kudocards/:/app
      - backend_node_modules:/app/node_modules


  db:
    image: mysql:8.0.20
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    restart: "no"
    env_file:
      - .envs/db.env
    ports:
      - ${DB_PUBLISH_PORT}:3306
    volumes:
      - ${DB_DATA_VOLUME}:/var/lib/mysql
    networks:
      - default

  adminer:
    image: adminer:4.7.7
    depends_on:
      - db
    environment:
      - 'ADMINER_DEFAULT_SERVER=db'
    restart: "no"
    ports:
      - "${ADMINER_PUBLISH_PORT}:8080"
    networks:
      - default
    volumes:
      - adminer:/sessions
